;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-69                      |
; |                             hi@hex-rays.com                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 3C65CCB278E995CCFF33017FEDF23EE4ED9420514B49FF2DF884B2ADCF3E9CDF
; Input MD5    : 43CDD4A59A0640BFEBBA1CC0D3A06A14
; Input CRC32  : 0D15D28D

; File Name   : /home/brox/Projects/zeliard/game/0/mao1.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 059Dh Loaded length: 059Dh

                .286
                .model small

; ===========================================================================

; Segment type: Pure code
seg000          segment byte public 'CODE'
                assume cs:seg000
                ;org 0A000h
                assume es:nothing, ss:nothing, ds:seg000
                dw offset Mao1_AI_proc
                dw offset boss_x
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                dw offset unk_A03E
                dw offset unk_A08E
                dw offset unk_A0DE
                dw offset unk_A12E
                dw offset unk_A17E
                dw offset unk_A1CE
                dw offset unk_A219
unk_A03E        db    1
                db    1
                db    2
                db    3
                db    4
                db    1
                db    5
                db    6
                db  0Ch
                db    0
                db    1
                db    0
                db    0
                db  0Ah
                db  0Bh
                db    1
                db    0
                db    0
                db    8
                db    9
                db    1
                db  0Eh
                db    0
                db    0
                db    0
                db    1
                db    7
                db  0Dh
                db  0Fh
                db  10h
                db    1
                db    0
                db    0
                db    1
                db    2
                db    1
                db    3
                db    4
                db  11h
                db  12h
                db    1
                db    0
                db    0
                db  13h
                db    0
                db    1
                db  18h
                db  19h
                db  1Eh
                db    0
                db    1
                db  16h
                db  17h
                db  0Ah
                db  1Dh
                db    1
                db    0
                db  15h
                db  1Ch
                db    9
                db    1
                db  20h
                db    0
                db    0
                db    0
                db    1
                db    0
                db  14h
                db  1Ah
                db  1Bh
                db    1
                db    7
                db  1Fh
                db  0Fh
                db  10h
                db    1
                db  28h ; (
                db    0
                db  2Fh ; /
                db  30h ; 0
unk_A08E        db    1
                db  26h ; &
                db  27h ; '
                db  2Dh ; -
                db  2Eh ; .
                db    1
                db  13h
                db    0
                db  18h
                db  22h ; "
                db    1
                db    1
                db    2
                db    3
                db    4
                db    1
                db  11h
                db  12h
                db  16h
                db  21h ; !
                db    1
                db  24h ; $
                db  25h ; %
                db  2Bh ; +
                db  2Ch ; ,
                db    1
                db  34h ; 4
                db    0
                db    0
                db    0
                db    1
                db    0
                db  23h ; #
                db  29h ; )
                db  2Ah ; *
                db    1
                db  32h ; 2
                db  33h ; 3
                db  35h ; 5
                db  36h ; 6
                db    1
                db    0
                db  31h ; 1
                db    0
                db    0
                db    1
                db    0
                db    0
                db    2
                db    0
                db    1
                db    4
                db    0
                db  39h ; 9
                db  3Ah ; :
                db    1
                db  3Dh ; =
                db  3Eh ; >
                db  3Dh ; =
                db  42h ; B
                db    1
                db  3Dh ; =
                db  45h ; E
                db  48h ; H
                db  49h ; I
                db    1
                db  4Dh ; M
                db  4Eh ; N
                db  52h ; R
                db  53h ; S
                db    1
                db    0
                db    0
                db    0
                db    1
                db    1
                db    0
                db    3
                db  37h ; 7
                db  38h ; 8
unk_A0DE        db    1
                db  3Bh ; ;
                db  3Ch ; <
                db  3Fh ; ?
                db  40h ; @
                db    1
                db  43h ; C
                db  44h ; D
                db  46h ; F
                db  47h ; G
                db    1
                db  4Bh ; K
                db  4Ch ; L
                db  50h ; P
                db  51h ; Q
                db    1
                db    0
                db  4Ah ; J
                db    0
                db  4Fh ; O
                db    1
                db    0
                db    3
                db  54h ; T
                db  38h ; 8
                db    1
                db  57h ; W
                db  3Ch ; <
                db  58h ; X
                db  40h ; @
                db    1
                db  59h ; Y
                db  44h ; D
                db  46h ; F
                db  47h ; G
                db    1
                db  55h ; U
                db  56h ; V
                db    0
                db    0
                db    1
                db    0
                db    3
                db  5Dh ; ]
                db  38h ; 8
                db    1
                db  58h ; X
                db  3Ch ; <
                db  58h ; X
                db  40h ; @
                db    1
                db    0
                db    0
                db  5Bh ; [
                db  5Ch ; \
                db    1
                db    0
                db    0
                db    0
                db  5Ah ; Z
                db    1
                db    4
                db    0
                db  61h ; a
                db  3Ah ; :
                db    1
                db  62h ; b
                db  3Eh ; >
                db  3Dh ; =
                db  42h ; B
                db    1
                db    0
                db    3
                db  5Eh ; ^
                db  38h ; 8
                db    1
                db  5Fh ; _
                db  60h ; `
                db  58h ; X
                db  40h ; @
unk_A12E        db    1
                db    4
                db    0
                db  67h ; g
                db  68h ; h
                db    1
                db    0
                db    3
                db  65h ; e
                db  66h ; f
                db    1
                db    0
                db    0
                db  63h ; c
                db  64h ; d
                db    1
                db  6Ch ; l
                db  6Dh ; m
                db  6Fh ; o
                db  70h ; p
                db    1
                db  6Ah ; j
                db  6Bh ; k
                db  69h ; i
                db  6Eh ; n
                db    1
                db    0
                db  69h ; i
                db    0
                db    0
                db    1
                db  71h ; q
                db  45h ; E
                db  72h ; r
                db  73h ; s
                db    1
                db    0
                db  69h ; i
                db    0
                db  47h ; G
                db    1
                db  74h ; t
                db  75h ; u
                db  77h ; w
                db  78h ; x
                db    1
                db    0
                db  4Ch ; L
                db  76h ; v
                db  51h ; Q
                db    1
                db    4
                db    0
                db  83h
                db  84h
                db    1
                db  86h
                db  87h
                db  71h ; q
                db  88h
                db    1
                db  89h
                db  8Ah
                db  85h
                db  71h ; q
                db    1
                db    0
                db    0
                db  8Bh
                db    0
                db    1
                db  8Ch
                db  8Dh
                db  77h ; w
                db  8Eh
                db    1
                db  7Dh ; }
                db    3
                db  81h
                db  82h
unk_A17E        db    1
                db  80h
                db  71h ; q
                db  85h
                db  80h
                db    1
                db    0
                db  85h
                db    0
                db  47h ; G
                db    1
                db    0
                db    0
                db  41h ; A
                db  79h ; y
                db    1
                db  7Bh ; {
                db  7Ch ; |
                db  7Fh ; 
                db  80h
                db    1
                db    0
                db  7Ah ; z
                db    0
                db  7Eh ; ~
                db    1
                db    0
                db  85h
                db    0
                db    0
                db    1
                db    4
                db    0
                db 0A7h
                db    0
                db    1
                db 0ACh
                db 0ADh
                db 0B0h
                db 0B1h
                db    1
                db 0B4h
                db    0
                db 0B6h
                db    0
                db    1
                db  8Ch
                db  8Dh
                db  77h ; w
                db  8Eh
                db    1
                db  94h
                db    0
                db  9Ah
                db    1
                db    1
                db 0A0h
                db 0A1h
                db 0A5h
                db 0A6h
                db    1
                db 0AAh
                db 0ABh
                db 0AEh
                db 0AFh
                db    1
                db 0B2h
                db 0B3h
                db    0
                db 0B5h
                db    1
                db    0
                db  4Ch ; L
                db  76h ; v
                db  51h ; Q
                db    1
                db  92h
                db  93h
                db  98h
                db  99h
unk_A1CE        db    1
                db  9Eh
                db  9Fh
                db 0A3h
                db 0A4h
                db    1
                db 0A8h
                db 0A9h
                db    0
                db    0
                db    1
                db  90h
                db  91h
                db  96h
                db  97h
                db    1
                db  9Ch
                db  9Dh
                db    0
                db 0A2h
                db    1
                db    0
                db  8Fh
                db    0
                db  95h
                db    1
                db    0
                db  9Bh
                db    0
                db    0
                db    1
                db    0
                db    0
                db 0C4h
                db 0C5h
                db    1
                db    4
                db 0CAh
                db 0CFh
                db 0D0h
                db    1
                db 0ACh
                db 0ADh
                db 0B0h
                db 0B1h
                db    1
                db 0B4h
                db    0
                db 0B6h
                db    0
                db    1
                db  8Ch
                db  8Dh
                db  77h ; w
                db  8Eh
                db    1
                db 0BCh
                db 0BDh
                db 0C2h
                db 0C3h
                db    1
                db 0C9h
                db    3
                db    0
                db 0CEh
                db    1
                db    0
                db 0D1h
                db    0
                db 0D2h
                db    1
                db    0
                db 0B3h
                db    0
                db 0B5h
unk_A219        db    1
                db    0
                db    0
                db    0
                db 0B8h
                db    1
                db    0
                db    0
                db    0
                db 0B7h
                db    1
                db 0BAh
                db 0BBh
                db 0C0h
                db 0C1h
                db    1
                db    0
                db 0B9h
                db 0BEh
                db 0BFh
                db    1
                db 0C7h
                db 0C8h
                db 0CCh
                db 0CDh
                db    1
                db    0
                db 0C6h
                db    0
                db 0CBh
                db    1
                db    0
                db    0
                db    0
                db    7

; =============== S U B R O U T I N E =======================================


Mao1_AI_proc    proc near
                mov     si, ds:0C010h
                mov     byte_A599, 0

loc_A245:
                cmp     word ptr [si], 0FFFFh
                jz      short loc_A273
                mov     ax, [si]
                call    word ptr cs:6036h
                jb      short loc_A26A
                mov     [si+3], bl
                mov     ax, [si+2]
                call    word ptr cs:6028h
                mov     bl, byte_A599
                xor     bh, bh
                mov     al, [bx+0ED20h]
                mov     [di], al

loc_A26A:
                inc     byte_A599
                add     si, 10h
                jmp     short loc_A245
; ---------------------------------------------------------------------------

loc_A273:
                mov     si, ds:0C010h
                mov     word ptr [si], 0FFFFh
                inc     byte_A59C
                mov     al, byte_A59C
                mov     bx, offset byte_A3BB
                xlat
                or      al, al
                jns     short loc_A28D
                jmp     loc_A350
; ---------------------------------------------------------------------------

loc_A28D:
                mov     byte_A59B, al

loc_A290:
                mov     al, byte_A59B
                mov     dx, 10h
                cmp     al, 3
                jb      short loc_A29D
                mov     dx, 0Dh

loc_A29D:
                mov     boss_x, dx
                mov     byte_A599, 0
                mov     bl, byte_A59B
                xor     bh, bh
                add     bx, bx
                mov     di, cs:off_A495[bx]
                mov     bp, cs:off_A52F[bx]
                mov     ax, boss_x
                mov     si, ds:0C010h
                mov     cx, 6

loc_A2C2:
                push    cx
                push    ax
                call    word ptr cs:6036h
                pop     ax
                mov     byte_A59A, bl
                jnb     short loc_A2DE
                mov     cx, 8

loc_A2D3:
                rol     byte ptr ds:[bp+0], 1
                jnb     short loc_A2DA
                inc     di

loc_A2DA:
                loop    loc_A2D3
                jmp     short loc_A340
; ---------------------------------------------------------------------------

loc_A2DE:
                xor     cl, cl

loc_A2E0:
                push    cx
                push    ax
                rol     byte ptr ds:[bp+0], 1
                jnb     short loc_A337
                mov     [si], ax
                add     cl, cl
                mov     al, boss_y
                add     al, cl
                and     al, 3Fh
                mov     [si+2], al
                mov     al, byte_A59A
                mov     [si+3], al
                mov     al, [di]
                mov     ah, al
                shr     al, 1
                shr     al, 1
                shr     al, 1
                shr     al, 1
                mov     [si+4], al
                and     ah, 0Fh
                mov     [si+6], ah
                mov     byte ptr [si+5], 0
                push    di
                mov     ax, [si+2]
                call    word ptr cs:6028h
                mov     bl, byte_A599
                xor     bh, bh
                mov     al, bl
                or      al, 80h
                xchg    al, [di]
                mov     [bx-12E0h], al
                add     si, 10h
                inc     byte_A599
                pop     di
                inc     di

loc_A337:
                pop     ax
                pop     cx
                inc     cl
                cmp     cl, 8
                jnz     short loc_A2E0

loc_A340:
                inc     bp
                inc     ax
                inc     ax
                pop     cx
                loop    loc_A348
                jmp     short loc_A34B
; ---------------------------------------------------------------------------

loc_A348:
                jmp     loc_A2C2
; ---------------------------------------------------------------------------

loc_A34B:
                mov     word ptr [si], 0FFFFh
                retn
; ---------------------------------------------------------------------------

loc_A350:
                mov     dx, offset loc_A290
                push    dx
                mov     ah, al
                and     al, 0F0h
                cmp     al, 80h
                jz      short loc_A376
                cmp     al, 0C0h
                jz      short loc_A3A2
                cmp     al, 0E0h
                jz      short loc_A370
                cmp     ah, 0FFh
                jz      short loc_A36A
                retn
; ---------------------------------------------------------------------------

loc_A36A:
                mov     byte ptr ds:0E6h, 0
                retn
; ---------------------------------------------------------------------------

loc_A370:
                mov     byte ptr ds:0FF75h, 38h ; '8'
                retn
; ---------------------------------------------------------------------------

loc_A376:
                and     ah, 0Fh
                xor     bx, bx
                add     ah, ah
                mov     bl, ah
                mov     dx, off_A442[bx]
                push    si
                push    dx
                mov     bx, 0E1Eh
                mov     cx, 3410h
                mov     al, 0FFh
                call    word ptr cs:2000h
                pop     si
                lodsw
                add     ax, 3Ah ; ':'
                mov     bx, ax
                mov     cl, 22h ; '"'
                call    word ptr cs:202Ah
                pop     si
                retn
; ---------------------------------------------------------------------------

loc_A3A2:
                mov     al, 0FEh
                push    ds
                pop     es
                assume es:seg000
                mov     di, 0E939h
                mov     cx, 2

loc_A3AC:
                push    cx
                push    di
                mov     cx, 26
                rep stosb
                pop     di
                add     di, 28
                pop     cx
                loop    loc_A3AC
                retn
Mao1_AI_proc    endp ; sp-analysis failed

; ---------------------------------------------------------------------------
byte_A3BB       db 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80h, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                db 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0C0h, 0, 1, 1
                db 2, 2, 3, 3, 3, 3, 3, 81h, 3, 3, 3, 3, 3, 3, 3
                db 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
                db 3, 3, 3, 3, 3, 3, 3, 0C0h, 3, 3, 3, 4, 4, 5, 82h
                db 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
                db 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
                db 0C0h, 5, 5, 6, 6, 7, 0E0h, 8, 8, 9, 9, 0Ah, 0Ah, 0Ah, 0FFh
off_A442        dw offset unk_A448
                dw offset unk_A463
                dw offset unk_A47A
unk_A448        db    8
                db    0
aFinallyYouReac db 'Finally, you reached me.'
                db 0FFh
unk_A463        db  18h
                db    0
aIEnjoyedYourSh db 'I enjoyed your show.'
                db 0FFh
unk_A47A        db    8
                db    0
aComeOnILlKillY db 'Come on!  I\ll kill you.'
                db 0FFh
off_A495        dw offset byte_A4AB
                dw offset byte_A4B1
                dw offset byte_A4BA
                dw offset byte_A4C4
                dw offset byte_A4CF
                dw offset byte_A4DB
                dw offset byte_A4E8
                dw offset byte_A4F3
                dw offset byte_A4FF
                dw offset byte_A50E
                dw offset byte_A51F
byte_A4AB       db 5, 3, 4, 2, 0, 1
byte_A4B1       db 0Dh, 0Eh, 0Bh, 0Ch, 6, 7, 0Ah, 8, 9
byte_A4BA       db 18h, 16h, 17h, 12h, 13h, 14h, 15h, 11h, 10h, 0Fh
byte_A4C4       db 23h, 1Eh, 1Fh, 20h, 21h, 22h, 19h, 1Ah, 1Bh, 1Ch, 1Dh
byte_A4CF       db 27h, 23h, 1Eh, 24h, 25h, 26h, 22h, 19h, 1Ah, 1Bh, 1Ch, 1Dh
byte_A4DB       db 2Bh, 2Ah, 23h, 1Eh, 28h, 29h, 26h, 22h, 19h, 1Ah, 1Bh, 1Ch, 1Dh
byte_A4E8       db 23h, 1Eh, 2Eh, 2Fh, 26h, 22h, 19h, 2Ch, 2Dh, 1Ch, 1Dh
byte_A4F3       db 32h, 35h, 1Eh, 31h, 34h, 37h, 39h, 19h, 30h, 33h, 36h, 38h
byte_A4FF       db 44h, 42h, 43h, 45h, 1Eh, 3Fh, 40h, 41h, 39h, 19h, 3Ah, 3Bh, 3Ch, 3Eh, 3Dh
byte_A50E       db 54h, 55h, 52h, 53h, 4Fh, 50h, 51h, 4Ah, 4Bh, 4Ch, 4Dh, 4Eh, 19h, 46h, 47h, 48h, 49h
byte_A51F       db 61h, 63h, 65h, 60h, 62h, 64h, 5Bh, 5Ch, 5Dh, 5Eh, 4Eh, 56h, 57h, 58h, 59h, 5Ah
off_A52F        dw offset byte_A545
                dw offset byte_A54B
                dw offset byte_A551
                dw offset byte_A557
                dw offset byte_A55D
                dw offset byte_A563
                dw offset byte_A557
                dw offset byte_A569
                dw offset byte_A56F
                dw offset byte_A575
                dw offset byte_A57B
byte_A545       db 0, 0, 4, 0Ch, 8, 18h
byte_A54B       db 0, 0, 0Ch, 0Ch, 38h, 18h
byte_A551       db 0, 4, 0Ch, 3Ch, 18h, 8
byte_A557       db 0, 0, 4, 7Ch, 7Ch, 0
byte_A55D       db 0, 0, 14h, 7Ch, 7Ch, 0
byte_A563       db 0, 20h, 24h, 7Ch, 7Ch, 0
byte_A569       db 0, 0, 30h, 7Ch, 7Ch, 0
byte_A56F       db 0, 20h, 70h, 7Ch, 7Ch, 8
byte_A575       db 60h, 60h, 70h, 7Ch, 7Ch, 0
byte_A57B       db 0, 0E0h, 0E0h, 7Ch, 7Ch, 0
boss_x          dw 16
boss_y          db 1
                dw 250
                dw 200
                db    5
                db 0FFh
                dw offset unk_A58E
                db    0
                db    0
unk_A58E        db  11h
                db 0BBh
                db    2
aJashiin        db 7,'Jashiin'
byte_A599       db 0
byte_A59A       db 0
byte_A59B       db 0
byte_A59C       db 0
seg000          ends


                end
