;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-69                      |
; |                             hi@hex-rays.com                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 5EE01BD482AA2C77AFE9DA52152A9637163745FFFDF0CD3EBF17778855F526A9
; Input MD5    : 4A90759D7B5A6BAF192DB1B41EC163D3
; Input CRC32  : AB6E0EC1

; File Name   : /home/brox/Projects/zeliard/WORK/rokademo.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 05A8h Loaded length: 05A8h

                .286
                .model small

; ===========================================================================

; Segment type: Pure code
seg000          segment byte public 'CODE'
                assume cs:seg000
                ;org 0A000h
                assume es:nothing, ss:nothing, ds:seg000
                dw offset sub_A002

; =============== S U B R O U T I N E =======================================


sub_A002        proc near
                mov     si, offset vfs_mfan_msd
                mov     es, word ptr cs:0FF2Ch ; seg1
                mov     di, 3000h
                mov     al, 5           ; fn_5_load_music
                call    word ptr cs:10Ch
                mov     es, word ptr cs:0FF2Ch ; seg1
                mov     si, offset vfs_dman_grp
                mov     di, 6000h
                mov     al, 2
                call    word ptr cs:10Ch ; fn2_segmented_load
                push    ds
                mov     ds, word ptr cs:0FF2Ch ; seg1
                mov     si, 6000h
                mov     bp, 0D000h
                mov     cx, 100h
                call    word ptr cs:3028h ; Decompress_Tile_Data
                                        ;  DS:SI - compressed data (will be unpacked in place)
                                        ;  BP - transparency masks buffer
                                        ;  CX - number of 8x8 tiles to decompress
                pop     ds
                inc     byte ptr ds:0A0h ; Tears_of_Esmesanti_count
                mov     al, 0           ; small blue Tear
                cmp     byte ptr ds:0A0h, 9 ; Tears_of_Esmesanti_count
                jb      short loc_A04F
                mov     byte ptr ds:0A0h, 9 ; Tears_of_Esmesanti_count
                mov     al, 1           ; big red Tear

loc_A04F:
                mov     byte_A5A4, al
                mov     bx, 2552h
                call    word ptr cs:203Eh ; Render_Tear_Icon
                                        ; ; AL: tear index (0-small blue Tear, 1-large red Tear)
                                        ; ; BH: left margin
                                        ; ; BL: top margin
                and     byte ptr ds:0C2h, 0FEh
                mov     bx, 0C6Eh
                mov     cx, 0Dh

loc_A065:
                test    cx, 1
                jnz     short loc_A070
                mov     byte ptr ds:0FF75h, 1Ah ; soundFX_request

loc_A070:
                push    cx
                push    bx
                inc     byte ptr ds:0E7h ; hero_animation_phase
                and     byte ptr ds:0E7h, 3 ; hero_animation_phase
                call    sub_A407
                call    sub_A48F
                pop     bx
                cmp     bh, 24h ; '$'
                jz      short loc_A096
                push    bx
                mov     cx, 218h
                xor     al, al
                call    word ptr cs:2000h ; Draw_Bordered_Rectangle
                pop     bx
                add     bh, 2

loc_A096:
                pop     cx
                loop    loc_A065
                mov     byte ptr ds:0E7h, 4 ; hero_animation_phase
                mov     bx, 246Eh
                call    sub_A407
                mov     cx, 5

loc_A0A7:
                push    cx
                call    sub_A48F
                pop     cx
                loop    loc_A0A7
                mov     byte ptr ds:0E7h, 5 ; hero_animation_phase

loc_A0B3:
                mov     bx, 246Eh
                call    sub_A407
                call    sub_A48F
                call    sub_A48F
                inc     byte ptr ds:0E7h ; hero_animation_phase
                cmp     byte ptr ds:0E7h, 9 ; hero_animation_phase
                jb      short loc_A0B3
                mov     bx, 246Eh
                call    sub_A407
                call    word ptr cs:3024h ; Render_Status_Indicator
                xor     bh, bh
                mov     bl, ds:0A0h     ; Tears_of_Esmesanti_count
                dec     bx
                mov     al, byte_A569[bx]
                mov     byte_A59A, al
                mov     byte_A59B, 2
                call    sub_A4A3
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     byte_A5A5, 0

loc_A107:
                mov     al, byte_A5A5
                mov     bl, byte_A59C
                xor     bh, bh
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                inc     byte_A5A5
                cmp     byte_A5A5, 2
                jb      short loc_A107
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                sub     ah, 6
                mov     al, byte_A59D
                mov     cx, 1110h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     byte ptr ds:0FF75h, 1Bh ; soundFX_request
                mov     byte_A5A5, 0

loc_A162:
                mov     al, byte_A5A5
                or      al, 80h
                mov     bl, byte_A59C
                xor     bh, bh
                sub     bx, 18h
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                call    sub_A48F
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                sub     ah, 6
                mov     al, byte_A59D
                mov     cx, 1110h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                inc     byte_A5A5
                cmp     byte_A5A5, 2
                jb      short loc_A162
                mov     bx, 2552h
                mov     cx, 410h
                xor     al, al
                call    word ptr cs:2000h ; Draw_Bordered_Rectangle
                call    word ptr cs:3024h ; Render_Status_Indicator
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     byte_A5A5, 0

loc_A1D2:
                mov     al, byte_A5A5
                mov     bl, byte_A59C
                xor     bh, bh
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                inc     byte_A5A5
                cmp     byte_A5A5, 4
                jb      short loc_A1D2
                mov     byte_A5A7, 0C8h

loc_A20E:
                inc     byte_A5A6
                test    byte_A5A6, 1
                jnz     short loc_A232
                inc     byte_A5A5
                inc     byte_A5A7
                cmp     byte_A5A7, 3
                jb      short loc_A232
                mov     byte_A5A7, 0
                mov     byte ptr ds:0FF75h, 1Ch ; soundFX_request

loc_A232:
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                call    sub_A50A
                pushf
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     al, byte_A5A5
                and     al, 1
                add     al, 2
                mov     bl, byte_A59C
                xor     bh, bh
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                popf
                jnb     short loc_A20E
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                sub     ah, 6
                mov     al, byte_A59D
                mov     cx, 1110h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     byte ptr ds:0FF75h, 1Bh ; soundFX_request
                mov     byte_A5A5, 0

loc_A2BB:
                mov     al, byte_A5A5
                or      al, 80h
                mov     bl, byte_A59C
                xor     bh, bh
                sub     bx, 18h
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                call    sub_A48F
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                sub     ah, 6
                mov     al, byte_A59D
                mov     cx, 1110h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                inc     byte_A5A5
                cmp     byte_A5A5, 2
                jb      short loc_A2BB
                mov     al, byte_A5A4
                mov     bl, ds:0A0h     ; Tears_of_Esmesanti_count
                dec     bl
                xor     bh, bh
                add     bx, bx
                mov     bx, tears_coords[bx]
                call    word ptr cs:203Eh ; Render_Tear_Icon
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2026h ; Capture_Screen_Rect_to_seg3
                mov     byte_A5A5, 4

loc_A32F:
                mov     al, byte_A5A5
                dec     al
                mov     bl, byte_A59C
                xor     bh, bh
                mov     cl, byte_A59D
                call    word ptr cs:3026h ; Render_Entity_Sprite
                call    sub_A48F
                mov     ah, byte_A59C
                shr     ah, 1
                shr     ah, 1
                shr     ah, 1
                mov     al, byte_A59D
                mov     cx, 310h
                xor     di, di
                call    word ptr cs:2028h ; Put_Image
                dec     byte_A5A5
                jnz     short loc_A32F
                push    ds
                mov     ds, word ptr cs:0FF2Ch ; seg1
                mov     si, 3000h
                xor     ax, ax
                int     60h             ; adlib fn 0
                pop     ds

loc_A371:                               ;
                test    byte ptr ds:0FF26h, 0FFh ; music_status_flag
                jz      short loc_A371
                mov     ax, 1
                int     60h             ; adlib fn_1
                mov     bx, 2456h
                mov     cx, 618h
                xor     al, al
                call    word ptr cs:2000h ; Draw_Bordered_Rectangle
                mov     byte ptr ds:0E7h, 8 ; hero_animation_phase

loc_A38F:
                mov     bx, 246Eh
                call    sub_A407
                call    sub_A48F
                call    sub_A48F
                dec     byte ptr ds:0E7h ; hero_animation_phase
                cmp     byte ptr ds:0E7h, 5 ; hero_animation_phase
                jnb     short loc_A38F
                mov     bx, 246Eh
                call    sub_A407
                mov     cx, 5

loc_A3AF:
                push    cx
                call    sub_A48F
                pop     cx
                loop    loc_A3AF
                mov     bx, 246Eh
                mov     cx, 218h
                xor     al, al
                call    word ptr cs:2000h ; Draw_Bordered_Rectangle
                mov     bx, 266Eh
                mov     cx, 0Dh

loc_A3C9:
                test    cx, 1
                jnz     short loc_A3D4
                mov     byte ptr ds:0FF75h, 1Ah ; soundFX_request

loc_A3D4:
                push    cx
                push    bx
                inc     byte ptr ds:0E7h ; hero_animation_phase
                and     byte ptr ds:0E7h, 3 ; hero_animation_phase
                call    sub_A407
                call    sub_A48F
                pop     bx
                cmp     bh, 3Eh ; '>'
                jz      short loc_A3FA
                push    bx
                mov     cx, 218h
                xor     al, al
                call    word ptr cs:2000h ; Draw_Bordered_Rectangle
                pop     bx
                add     bh, 2

loc_A3FA:
                pop     cx
                loop    loc_A3C9
                mov     cx, 618h
                xor     al, al
                jmp     word ptr cs:2000h ; Draw_Bordered_Rectangle
sub_A002        endp


; =============== S U B R O U T I N E =======================================


sub_A407        proc near
                mov     al, ds:0E7h     ; hero_animation_phase
                mov     cl, 9
                mul     cl
                add     ax, offset tiles_grouping3x3
                mov     si, ax
                mov     cx, 3

loc_A416:
                push    cx
                mov     cx, 3

loc_A41A:
                push    cx
                lodsb
                push    si
                push    bx
                call    word ptr cs:3022h ; Render_16x16_Sprite
                pop     bx
                pop     si
                add     bl, 8
                pop     cx
                loop    loc_A41A
                sub     bl, 18h
                add     bh, 2
                pop     cx
                loop    loc_A416
                retn
sub_A407        endp

; ---------------------------------------------------------------------------
tiles_grouping3x3 db 0, 2, 4, 1, 3, 5, 0, 0, 6
                db 7, 9, 11, 8, 10, 12, 0, 0, 0
                db 0, 2, 14, 1, 13, 15, 0, 0, 16
                db 7, 9, 17, 8, 10, 18, 0, 0, 0
                db 0, 20, 22, 19, 21, 23, 0, 0, 24
                db 25, 0, 28, 26, 27, 29, 0, 0, 30
                db 31, 0, 35, 32, 33, 36, 0, 34, 37
                db 31, 0, 35, 32, 38, 40, 0, 39, 41
                db 31, 0, 35, 42, 44, 40, 43, 45, 41
                db 46, 49, 35, 47, 50, 52, 48, 51, 53

; =============== S U B R O U T I N E =======================================


sub_A48F        proc near
                mov     cl, ds:0FF33h   ; speed_const
                mov     al, 4
                mul     cl

loc_A497:                               ;
                cmp     ds:0FF1Ah, al   ; frame_timer
                jb      short loc_A497
                mov     byte ptr ds:0FF1Ah, 0 ; frame_timer
                retn
sub_A48F        endp


; =============== S U B R O U T I N E =======================================


sub_A4A3        proc near
                mov     byte_A59C, 94h
                mov     byte_A59D, 50h ; 'P'
                xor     cl, cl
                mov     al, byte_A59A
                sub     al, byte_A59C
                jz      short loc_A4C2
                jnb     short loc_A4C0
                neg     al
                dec     cl
                jmp     short loc_A4C2
; ---------------------------------------------------------------------------

loc_A4C0:
                inc     cl

loc_A4C2:
                mov     byte_A5A0, al
                mov     byte_A59E, cl
                xor     cl, cl
                mov     al, byte_A59B
                sub     al, byte_A59D
                jz      short loc_A4DE
                jnb     short loc_A4DC
                neg     al
                dec     cl
                jmp     short loc_A4DE
; ---------------------------------------------------------------------------

loc_A4DC:
                inc     cl

loc_A4DE:
                mov     byte_A5A1, al
                mov     byte_A59F, cl
                mov     al, byte_A5A0
                shr     al, 1
                mov     byte_A5A3, al
                mov     byte_A5A2, 0
                mov     al, byte_A5A0
                cmp     al, byte_A5A1
                jb      short loc_A4FC
                retn
; ---------------------------------------------------------------------------

loc_A4FC:
                mov     al, byte_A5A1
                shr     al, 1
                mov     byte_A5A3, al
                mov     byte_A5A2, 0FFh
                retn
sub_A4A3        endp


; =============== S U B R O U T I N E =======================================


sub_A50A        proc near
                test    byte_A5A2, 0FFh
                jnz     short loc_A53D
                mov     al, byte_A5A3
                sub     al, byte_A5A1
                jnb     short loc_A526
                add     al, byte_A5A0
                mov     ah, byte_A59F
                add     byte_A59D, ah

loc_A526:
                mov     byte_A5A3, al
                mov     al, byte_A59E
                add     byte_A59C, al
                mov     al, byte_A59A
                cmp     al, byte_A59C
                stc
                jnz     short loc_A53B
                retn
; ---------------------------------------------------------------------------

loc_A53B:
                clc
                retn
; ---------------------------------------------------------------------------

loc_A53D:
                mov     al, byte_A5A3
                sub     al, byte_A5A0
                jnb     short loc_A552
                add     al, byte_A5A1
                mov     ah, byte_A59E
                add     byte_A59C, ah

loc_A552:
                mov     byte_A5A3, al
                mov     al, byte_A59F
                add     byte_A59D, al
                mov     al, byte_A59B
                cmp     al, byte_A59D
                stc
                jnz     short loc_A567
                retn
; ---------------------------------------------------------------------------

loc_A567:
                clc
                retn
sub_A50A        endp

; ---------------------------------------------------------------------------
byte_A569       db 3Ch, 0F4h, 54h, 0DCh, 6Ch, 0C4h, 84h, 0ACh, 98h
tears_coords    dw 0F00h, 3D00h, 1500h, 3700h, 1B00h, 3100h, 2100h, 2B00h, 2600h
vfs_mfan_msd    db 2
                db 5Fh
aMfanMsd        db 'MFAN.MSD',0
vfs_dman_grp    db 2
                db 36h
aDmanGrp        db 'DMAN.GRP',0
byte_A59A       db 0
byte_A59B       db 0
byte_A59C       db 0
byte_A59D       db 0
byte_A59E       db 0
byte_A59F       db 0
byte_A5A0       db 0
byte_A5A1       db 0
byte_A5A2       db 0
byte_A5A3       db 0
byte_A5A4       db 0
byte_A5A5       db 0
byte_A5A6       db 0
byte_A5A7       db 0
seg000          ends


                end
